In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [11]:
df = pd.DataFrame({
    'feature': [0.2, -1.1, 1.6, 5.4],
    'labels':[1,1,0,2]
})

In [12]:
df = df.rename(columns={'labels':'label'})

In [13]:
df

   feature  label
0      0.2      1
1     -1.1      1
2      1.6      0
3      5.4      2

In [14]:
iris = sns.load_dataset('iris')

In [15]:
iris.sort_values('species', ascending=False)

     sepal_length  sepal_width  petal_length  petal_width    species
149           5.9          3.0           5.1          1.8  virginica
111           6.4          2.7           5.3          1.9  virginica
122           7.7          2.8           6.7          2.0  virginica
121           5.6          2.8           4.9          2.0  virginica
120           6.9          3.2           5.7          2.3  virginica
..            ...          ...           ...          ...        ...
31            5.4          3.4           1.5          0.4     setosa
30            4.8          3.1           1.6          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
0             5.1          3.5           1.4          0.2     setosa

[150 rows x 5 columns]

In [20]:
iris.value_counts('species').to_frame('n')

             n
species
setosa      50
versicolor  50
virginica   50

In [22]:
len(iris[(iris.petal_length <= 1.4) | (iris.petal_length >=1.6)])

137

In [24]:
iris['min_petal'] = iris.apply(lambda x:min(x.petal_length, x.petal_width), axis=1)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  min_petal
0           5.1          3.5           1.4          0.2  setosa        0.2
1           4.9          3.0           1.4          0.2  setosa        0.2
2           4.7          3.2           1.3          0.2  setosa        0.2
3           4.6          3.1           1.5          0.2  setosa        0.2
4           5.0          3.6           1.4          0.2  setosa        0.2

In [27]:
pd.pivot_table(iris,
               values = ["sepal_width", "petal_width"],
               columns = ["species"],
               aggfunc = {np.mean, np.median})

species             setosa  versicolor  virginica
petal_width mean     0.246       1.326      2.026
            median   0.200       1.300      2.000
sepal_width mean     3.428       2.770      2.974
            median   3.400       2.800      3.000